#pragma once

#include "M128.h"

#include <xmmintrin.h>
#include <smmintrin.h>

namespace ray
{
    namespace m128
    {
        template <unsigned X, unsigned Y, unsigned Z, unsigned W>
        inline __m128 perm(__m128 v)
        {
            static_assert(X < 4 && Y < 4 && Z < 4 && W < 4);
            return _mm_shuffle_ps(v, v, _MM_SHUFFLE(W, Z, Y, X));
        }

        template <unsigned X, unsigned Y, unsigned Z, unsigned W>
        inline __m128 shuffle(__m128 a, __m128 b)
        {
            static_assert(X < 4 && Y < 4 && Z < 4 && W < 4);
            return _mm_shuffle_ps(a, b, _MM_SHUFFLE(W, Z, Y, X));
        }

#define RAY_GEN_M128_SWIZZLE(X, Y, Z, W) \
inline __m128 perm_##X##Y##Z##W(__m128 v) { return perm<m128::lane::##X, m128::lane::##Y, m128::lane::##Z, m128::lane::##W>(v); } \
inline __m128 shuffle_##X##Y##Z##W(__m128 a, __m128 b) { return shuffle<m128::lane::##X, m128::lane::##Y, m128::lane::##Z, m128::lane::##W>(a, b); }

        // TODO: see if the compiler can optimize less complex shuffles into other instructions
        //       if not then do it manually

        RAY_GEN_M128_SWIZZLE(x, x, x, x)
        RAY_GEN_M128_SWIZZLE(x, x, x, y)
        RAY_GEN_M128_SWIZZLE(x, x, x, z)
        RAY_GEN_M128_SWIZZLE(x, x, x, w)
        RAY_GEN_M128_SWIZZLE(x, x, y, x)
        RAY_GEN_M128_SWIZZLE(x, x, y, y)
        RAY_GEN_M128_SWIZZLE(x, x, y, z)
        RAY_GEN_M128_SWIZZLE(x, x, y, w)
        RAY_GEN_M128_SWIZZLE(x, x, z, x)
        RAY_GEN_M128_SWIZZLE(x, x, z, y)
        RAY_GEN_M128_SWIZZLE(x, x, z, z)
        RAY_GEN_M128_SWIZZLE(x, x, z, w)
        RAY_GEN_M128_SWIZZLE(x, x, w, x)
        RAY_GEN_M128_SWIZZLE(x, x, w, y)
        RAY_GEN_M128_SWIZZLE(x, x, w, z)
        RAY_GEN_M128_SWIZZLE(x, x, w, w)
        RAY_GEN_M128_SWIZZLE(x, y, x, x)
        RAY_GEN_M128_SWIZZLE(x, y, x, y)
        RAY_GEN_M128_SWIZZLE(x, y, x, z)
        RAY_GEN_M128_SWIZZLE(x, y, x, w)
        RAY_GEN_M128_SWIZZLE(x, y, y, x)
        RAY_GEN_M128_SWIZZLE(x, y, y, y)
        RAY_GEN_M128_SWIZZLE(x, y, y, z)
        RAY_GEN_M128_SWIZZLE(x, y, y, w)
        RAY_GEN_M128_SWIZZLE(x, y, z, x)
        RAY_GEN_M128_SWIZZLE(x, y, z, y)
        RAY_GEN_M128_SWIZZLE(x, y, z, z)
        RAY_GEN_M128_SWIZZLE(x, y, z, w)
        RAY_GEN_M128_SWIZZLE(x, y, w, x)
        RAY_GEN_M128_SWIZZLE(x, y, w, y)
        RAY_GEN_M128_SWIZZLE(x, y, w, z)
        RAY_GEN_M128_SWIZZLE(x, y, w, w)
        RAY_GEN_M128_SWIZZLE(x, z, x, x)
        RAY_GEN_M128_SWIZZLE(x, z, x, y)
        RAY_GEN_M128_SWIZZLE(x, z, x, z)
        RAY_GEN_M128_SWIZZLE(x, z, x, w)
        RAY_GEN_M128_SWIZZLE(x, z, y, x)
        RAY_GEN_M128_SWIZZLE(x, z, y, y)
        RAY_GEN_M128_SWIZZLE(x, z, y, z)
        RAY_GEN_M128_SWIZZLE(x, z, y, w)
        RAY_GEN_M128_SWIZZLE(x, z, z, x)
        RAY_GEN_M128_SWIZZLE(x, z, z, y)
        RAY_GEN_M128_SWIZZLE(x, z, z, z)
        RAY_GEN_M128_SWIZZLE(x, z, z, w)
        RAY_GEN_M128_SWIZZLE(x, z, w, x)
        RAY_GEN_M128_SWIZZLE(x, z, w, y)
        RAY_GEN_M128_SWIZZLE(x, z, w, z)
        RAY_GEN_M128_SWIZZLE(x, z, w, w)
        RAY_GEN_M128_SWIZZLE(x, w, x, x)
        RAY_GEN_M128_SWIZZLE(x, w, x, y)
        RAY_GEN_M128_SWIZZLE(x, w, x, z)
        RAY_GEN_M128_SWIZZLE(x, w, x, w)
        RAY_GEN_M128_SWIZZLE(x, w, y, x)
        RAY_GEN_M128_SWIZZLE(x, w, y, y)
        RAY_GEN_M128_SWIZZLE(x, w, y, z)
        RAY_GEN_M128_SWIZZLE(x, w, y, w)
        RAY_GEN_M128_SWIZZLE(x, w, z, x)
        RAY_GEN_M128_SWIZZLE(x, w, z, y)
        RAY_GEN_M128_SWIZZLE(x, w, z, z)
        RAY_GEN_M128_SWIZZLE(x, w, z, w)
        RAY_GEN_M128_SWIZZLE(x, w, w, x)
        RAY_GEN_M128_SWIZZLE(x, w, w, y)
        RAY_GEN_M128_SWIZZLE(x, w, w, z)
        RAY_GEN_M128_SWIZZLE(x, w, w, w)
        RAY_GEN_M128_SWIZZLE(y, x, x, x)
        RAY_GEN_M128_SWIZZLE(y, x, x, y)
        RAY_GEN_M128_SWIZZLE(y, x, x, z)
        RAY_GEN_M128_SWIZZLE(y, x, x, w)
        RAY_GEN_M128_SWIZZLE(y, x, y, x)
        RAY_GEN_M128_SWIZZLE(y, x, y, y)
        RAY_GEN_M128_SWIZZLE(y, x, y, z)
        RAY_GEN_M128_SWIZZLE(y, x, y, w)
        RAY_GEN_M128_SWIZZLE(y, x, z, x)
        RAY_GEN_M128_SWIZZLE(y, x, z, y)
        RAY_GEN_M128_SWIZZLE(y, x, z, z)
        RAY_GEN_M128_SWIZZLE(y, x, z, w)
        RAY_GEN_M128_SWIZZLE(y, x, w, x)
        RAY_GEN_M128_SWIZZLE(y, x, w, y)
        RAY_GEN_M128_SWIZZLE(y, x, w, z)
        RAY_GEN_M128_SWIZZLE(y, x, w, w)
        RAY_GEN_M128_SWIZZLE(y, y, x, x)
        RAY_GEN_M128_SWIZZLE(y, y, x, y)
        RAY_GEN_M128_SWIZZLE(y, y, x, z)
        RAY_GEN_M128_SWIZZLE(y, y, x, w)
        RAY_GEN_M128_SWIZZLE(y, y, y, x)
        RAY_GEN_M128_SWIZZLE(y, y, y, y)
        RAY_GEN_M128_SWIZZLE(y, y, y, z)
        RAY_GEN_M128_SWIZZLE(y, y, y, w)
        RAY_GEN_M128_SWIZZLE(y, y, z, x)
        RAY_GEN_M128_SWIZZLE(y, y, z, y)
        RAY_GEN_M128_SWIZZLE(y, y, z, z)
        RAY_GEN_M128_SWIZZLE(y, y, z, w)
        RAY_GEN_M128_SWIZZLE(y, y, w, x)
        RAY_GEN_M128_SWIZZLE(y, y, w, y)
        RAY_GEN_M128_SWIZZLE(y, y, w, z)
        RAY_GEN_M128_SWIZZLE(y, y, w, w)
        RAY_GEN_M128_SWIZZLE(y, z, x, x)
        RAY_GEN_M128_SWIZZLE(y, z, x, y)
        RAY_GEN_M128_SWIZZLE(y, z, x, z)
        RAY_GEN_M128_SWIZZLE(y, z, x, w)
        RAY_GEN_M128_SWIZZLE(y, z, y, x)
        RAY_GEN_M128_SWIZZLE(y, z, y, y)
        RAY_GEN_M128_SWIZZLE(y, z, y, z)
        RAY_GEN_M128_SWIZZLE(y, z, y, w)
        RAY_GEN_M128_SWIZZLE(y, z, z, x)
        RAY_GEN_M128_SWIZZLE(y, z, z, y)
        RAY_GEN_M128_SWIZZLE(y, z, z, z)
        RAY_GEN_M128_SWIZZLE(y, z, z, w)
        RAY_GEN_M128_SWIZZLE(y, z, w, x)
        RAY_GEN_M128_SWIZZLE(y, z, w, y)
        RAY_GEN_M128_SWIZZLE(y, z, w, z)
        RAY_GEN_M128_SWIZZLE(y, z, w, w)
        RAY_GEN_M128_SWIZZLE(y, w, x, x)
        RAY_GEN_M128_SWIZZLE(y, w, x, y)
        RAY_GEN_M128_SWIZZLE(y, w, x, z)
        RAY_GEN_M128_SWIZZLE(y, w, x, w)
        RAY_GEN_M128_SWIZZLE(y, w, y, x)
        RAY_GEN_M128_SWIZZLE(y, w, y, y)
        RAY_GEN_M128_SWIZZLE(y, w, y, z)
        RAY_GEN_M128_SWIZZLE(y, w, y, w)
        RAY_GEN_M128_SWIZZLE(y, w, z, x)
        RAY_GEN_M128_SWIZZLE(y, w, z, y)
        RAY_GEN_M128_SWIZZLE(y, w, z, z)
        RAY_GEN_M128_SWIZZLE(y, w, z, w)
        RAY_GEN_M128_SWIZZLE(y, w, w, x)
        RAY_GEN_M128_SWIZZLE(y, w, w, y)
        RAY_GEN_M128_SWIZZLE(y, w, w, z)
        RAY_GEN_M128_SWIZZLE(y, w, w, w)
        RAY_GEN_M128_SWIZZLE(z, x, x, x)
        RAY_GEN_M128_SWIZZLE(z, x, x, y)
        RAY_GEN_M128_SWIZZLE(z, x, x, z)
        RAY_GEN_M128_SWIZZLE(z, x, x, w)
        RAY_GEN_M128_SWIZZLE(z, x, y, x)
        RAY_GEN_M128_SWIZZLE(z, x, y, y)
        RAY_GEN_M128_SWIZZLE(z, x, y, z)
        RAY_GEN_M128_SWIZZLE(z, x, y, w)
        RAY_GEN_M128_SWIZZLE(z, x, z, x)
        RAY_GEN_M128_SWIZZLE(z, x, z, y)
        RAY_GEN_M128_SWIZZLE(z, x, z, z)
        RAY_GEN_M128_SWIZZLE(z, x, z, w)
        RAY_GEN_M128_SWIZZLE(z, x, w, x)
        RAY_GEN_M128_SWIZZLE(z, x, w, y)
        RAY_GEN_M128_SWIZZLE(z, x, w, z)
        RAY_GEN_M128_SWIZZLE(z, x, w, w)
        RAY_GEN_M128_SWIZZLE(z, y, x, x)
        RAY_GEN_M128_SWIZZLE(z, y, x, y)
        RAY_GEN_M128_SWIZZLE(z, y, x, z)
        RAY_GEN_M128_SWIZZLE(z, y, x, w)
        RAY_GEN_M128_SWIZZLE(z, y, y, x)
        RAY_GEN_M128_SWIZZLE(z, y, y, y)
        RAY_GEN_M128_SWIZZLE(z, y, y, z)
        RAY_GEN_M128_SWIZZLE(z, y, y, w)
        RAY_GEN_M128_SWIZZLE(z, y, z, x)
        RAY_GEN_M128_SWIZZLE(z, y, z, y)
        RAY_GEN_M128_SWIZZLE(z, y, z, z)
        RAY_GEN_M128_SWIZZLE(z, y, z, w)
        RAY_GEN_M128_SWIZZLE(z, y, w, x)
        RAY_GEN_M128_SWIZZLE(z, y, w, y)
        RAY_GEN_M128_SWIZZLE(z, y, w, z)
        RAY_GEN_M128_SWIZZLE(z, y, w, w)
        RAY_GEN_M128_SWIZZLE(z, z, x, x)
        RAY_GEN_M128_SWIZZLE(z, z, x, y)
        RAY_GEN_M128_SWIZZLE(z, z, x, z)
        RAY_GEN_M128_SWIZZLE(z, z, x, w)
        RAY_GEN_M128_SWIZZLE(z, z, y, x)
        RAY_GEN_M128_SWIZZLE(z, z, y, y)
        RAY_GEN_M128_SWIZZLE(z, z, y, z)
        RAY_GEN_M128_SWIZZLE(z, z, y, w)
        RAY_GEN_M128_SWIZZLE(z, z, z, x)
        RAY_GEN_M128_SWIZZLE(z, z, z, y)
        RAY_GEN_M128_SWIZZLE(z, z, z, z)
        RAY_GEN_M128_SWIZZLE(z, z, z, w)
        RAY_GEN_M128_SWIZZLE(z, z, w, x)
        RAY_GEN_M128_SWIZZLE(z, z, w, y)
        RAY_GEN_M128_SWIZZLE(z, z, w, z)
        RAY_GEN_M128_SWIZZLE(z, z, w, w)
        RAY_GEN_M128_SWIZZLE(z, w, x, x)
        RAY_GEN_M128_SWIZZLE(z, w, x, y)
        RAY_GEN_M128_SWIZZLE(z, w, x, z)
        RAY_GEN_M128_SWIZZLE(z, w, x, w)
        RAY_GEN_M128_SWIZZLE(z, w, y, x)
        RAY_GEN_M128_SWIZZLE(z, w, y, y)
        RAY_GEN_M128_SWIZZLE(z, w, y, z)
        RAY_GEN_M128_SWIZZLE(z, w, y, w)
        RAY_GEN_M128_SWIZZLE(z, w, z, x)
        RAY_GEN_M128_SWIZZLE(z, w, z, y)
        RAY_GEN_M128_SWIZZLE(z, w, z, z)
        RAY_GEN_M128_SWIZZLE(z, w, z, w)
        RAY_GEN_M128_SWIZZLE(z, w, w, x)
        RAY_GEN_M128_SWIZZLE(z, w, w, y)
        RAY_GEN_M128_SWIZZLE(z, w, w, z)
        RAY_GEN_M128_SWIZZLE(z, w, w, w)
        RAY_GEN_M128_SWIZZLE(w, x, x, x)
        RAY_GEN_M128_SWIZZLE(w, x, x, y)
        RAY_GEN_M128_SWIZZLE(w, x, x, z)
        RAY_GEN_M128_SWIZZLE(w, x, x, w)
        RAY_GEN_M128_SWIZZLE(w, x, y, x)
        RAY_GEN_M128_SWIZZLE(w, x, y, y)
        RAY_GEN_M128_SWIZZLE(w, x, y, z)
        RAY_GEN_M128_SWIZZLE(w, x, y, w)
        RAY_GEN_M128_SWIZZLE(w, x, z, x)
        RAY_GEN_M128_SWIZZLE(w, x, z, y)
        RAY_GEN_M128_SWIZZLE(w, x, z, z)
        RAY_GEN_M128_SWIZZLE(w, x, z, w)
        RAY_GEN_M128_SWIZZLE(w, x, w, x)
        RAY_GEN_M128_SWIZZLE(w, x, w, y)
        RAY_GEN_M128_SWIZZLE(w, x, w, z)
        RAY_GEN_M128_SWIZZLE(w, x, w, w)
        RAY_GEN_M128_SWIZZLE(w, y, x, x)
        RAY_GEN_M128_SWIZZLE(w, y, x, y)
        RAY_GEN_M128_SWIZZLE(w, y, x, z)
        RAY_GEN_M128_SWIZZLE(w, y, x, w)
        RAY_GEN_M128_SWIZZLE(w, y, y, x)
        RAY_GEN_M128_SWIZZLE(w, y, y, y)
        RAY_GEN_M128_SWIZZLE(w, y, y, z)
        RAY_GEN_M128_SWIZZLE(w, y, y, w)
        RAY_GEN_M128_SWIZZLE(w, y, z, x)
        RAY_GEN_M128_SWIZZLE(w, y, z, y)
        RAY_GEN_M128_SWIZZLE(w, y, z, z)
        RAY_GEN_M128_SWIZZLE(w, y, z, w)
        RAY_GEN_M128_SWIZZLE(w, y, w, x)
        RAY_GEN_M128_SWIZZLE(w, y, w, y)
        RAY_GEN_M128_SWIZZLE(w, y, w, z)
        RAY_GEN_M128_SWIZZLE(w, y, w, w)
        RAY_GEN_M128_SWIZZLE(w, z, x, x)
        RAY_GEN_M128_SWIZZLE(w, z, x, y)
        RAY_GEN_M128_SWIZZLE(w, z, x, z)
        RAY_GEN_M128_SWIZZLE(w, z, x, w)
        RAY_GEN_M128_SWIZZLE(w, z, y, x)
        RAY_GEN_M128_SWIZZLE(w, z, y, y)
        RAY_GEN_M128_SWIZZLE(w, z, y, z)
        RAY_GEN_M128_SWIZZLE(w, z, y, w)
        RAY_GEN_M128_SWIZZLE(w, z, z, x)
        RAY_GEN_M128_SWIZZLE(w, z, z, y)
        RAY_GEN_M128_SWIZZLE(w, z, z, z)
        RAY_GEN_M128_SWIZZLE(w, z, z, w)
        RAY_GEN_M128_SWIZZLE(w, z, w, x)
        RAY_GEN_M128_SWIZZLE(w, z, w, y)
        RAY_GEN_M128_SWIZZLE(w, z, w, z)
        RAY_GEN_M128_SWIZZLE(w, z, w, w)
        RAY_GEN_M128_SWIZZLE(w, w, x, x)
        RAY_GEN_M128_SWIZZLE(w, w, x, y)
        RAY_GEN_M128_SWIZZLE(w, w, x, z)
        RAY_GEN_M128_SWIZZLE(w, w, x, w)
        RAY_GEN_M128_SWIZZLE(w, w, y, x)
        RAY_GEN_M128_SWIZZLE(w, w, y, y)
        RAY_GEN_M128_SWIZZLE(w, w, y, z)
        RAY_GEN_M128_SWIZZLE(w, w, y, w)
        RAY_GEN_M128_SWIZZLE(w, w, z, x)
        RAY_GEN_M128_SWIZZLE(w, w, z, y)
        RAY_GEN_M128_SWIZZLE(w, w, z, z)
        RAY_GEN_M128_SWIZZLE(w, w, z, w)
        RAY_GEN_M128_SWIZZLE(w, w, w, x)
        RAY_GEN_M128_SWIZZLE(w, w, w, y)
        RAY_GEN_M128_SWIZZLE(w, w, w, z)
        RAY_GEN_M128_SWIZZLE(w, w, w, w)

#undef RAY_GEN_M128_SWIZZLE
    }
}
